# Generated by Django 4.1.4 on 2023-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
    ]
